import { defineFormSchema } from '#ui-tools/form'

export function parityFormSchema() {
  return defineFormSchema({
    actions: [
      { key: 'cancel', label: 'Annuler' },
      { key: 'submit', label: 'Enregistrer' },
    ],
    fields: [
      { key: 'identifiers', label: 'Identifiants', type: 'section' },
      {
        description: { display: 'tooltip', text: 'Format contrôlé selon le pays' },
        key: 'vat',
        label: 'Numéro de TVA',
        mask: 'AA## ### ### ###',
        mono: true,
        placeholder: 'FR00 000 000 000',
        type: 'text',
      },
      {
        key: 'siren',
        label: 'N° d’enregistrement (SIREN)',
        mask: '### ### ###',
        maskOutput: 'raw',
        mono: true,
        placeholder: '000 000 000',
        type: 'text',
      },
      {
        clearable: true,
        description: {
          display: 'modal',
          text: 'Identifiant du compte dans Evoliz. Il est rempli par la synchronisation et reste modifiable à la main si besoin.',
          title: 'ERP ID',
        },
        icon: 'i-lucide-arrow-left-right',
        key: 'erpId',
        label: 'ERP ID (Evoliz)',
        mono: true,
        placeholder: 'Rempli par la synchronisation',
        type: 'text',
      },
      { key: 'pricing', label: 'Tarification', type: 'section' },
      {
        format: { maximumFractionDigits: 2, minimumFractionDigits: 2 },
        key: 'unitPrice',
        label: 'Prix unitaire',
        min: 0,
        suffix: '€',
        type: 'number',
      },
      {
        controls: false,
        key: 'volume',
        label: 'Volume',
        min: 0,
        suffix: 'tests',
        type: 'number',
      },
      {
        controls: false,
        format: { maximumFractionDigits: 4 },
        key: 'rate',
        label: 'Taux de change',
        prefix: '1 USD =',
        suffix: 'EUR',
        type: 'number',
      },
      { key: 'notesSection', label: 'Notes', type: 'section' },
      {
        autoresize: true,
        key: 'notes',
        label: 'Note interne',
        maxlength: 500,
        maxrows: 8,
        placeholder: 'Visible uniquement par l’équipe',
        rows: 2,
        type: 'textarea',
      },
      { key: 'productSection', label: 'Produit', type: 'section' },
      {
        key: 'product',
        tabs: [
          {
            fields: [
              { key: 'productName', label: 'Nom du produit', required: true, type: 'text' },
              {
                key: 'productLine',
                label: 'Gamme',
                options: [
                  { label: 'TOEIC', value: 'toeic' },
                  { label: 'Bright', value: 'bright' },
                ],
                type: 'select',
              },
              {
                key: 'productDescription',
                label: 'Description',
                layout: { span: 'full' },
                rows: 2,
                type: 'textarea',
              },
            ],
            key: 'general',
            label: 'Général',
          },
          {
            fields: [
              {
                key: 'listPrice',
                label: 'Prix catalogue',
                required: true,
                suffix: '€',
                type: 'number',
              },
              { key: 'validity', label: 'Validité (mois)', type: 'number' },
            ],
            key: 'pricing',
            label: 'Versions & tarifs',
          },
          {
            fields: [
              { key: 'scoreMax', label: 'Score maximal', type: 'number' },
              { key: 'certificate', label: 'Certificat délivré', type: 'checkbox' },
            ],
            key: 'results',
            label: 'Résultats',
          },
        ],
        type: 'tabs',
      },
      { key: 'choicesSection', label: 'Choix', type: 'section' },
      {
        key: 'accountType',
        label: 'Type de compte',
        layout: { span: 'full' },
        options: [
          {
            description: 'Achète des tests pour ses candidats',
            icon: 'i-lucide-building-2',
            label: 'Client',
            value: 'customer',
          },
          {
            description: 'Revend ou prescrit des tests',
            icon: 'i-lucide-handshake',
            label: 'Partenaire',
            value: 'partner',
          },
          {
            description: 'Fait passer les tests sur site',
            icon: 'i-lucide-school',
            label: 'Centre de test',
            value: 'testCenter',
          },
        ],
        orientation: 'horizontal',
        type: 'radio-card',
      },
      {
        key: 'scope',
        label: 'Périmètre de l’export',
        options: [
          { description: '154 comptes', label: 'Filtres courants', value: 'filters' },
          { description: '3 comptes', label: 'Sélection', value: 'selection' },
        ],
        type: 'radio',
        variant: 'card',
      },
      {
        key: 'levels',
        label: 'Niveaux (2 max)',
        max: 2,
        multiple: true,
        options: [
          { label: 'A1', value: 'A1' },
          { label: 'A2', value: 'A2' },
          { label: 'B1', value: 'B1' },
          { label: 'B2', value: 'B2' },
        ],
        type: 'select',
      },
      { key: 'documentsSection', label: 'Documents', type: 'section' },
      {
        accept: 'image/png,image/svg+xml',
        dropzoneDescription: 'PNG ou SVG, fond transparent recommandé',
        dropzoneLabel: 'Déposer une image ou parcourir',
        icon: 'i-lucide-image',
        key: 'logo',
        label: 'Logo',
        type: 'file',
        variant: 'area',
      },
      {
        accept: 'application/pdf',
        dropzoneDescription: 'PDF uniquement, 20 Mo maximum',
        dropzoneLabel: 'Déposer un PDF ou parcourir',
        key: 'kbis',
        label: 'Fichier d’enregistrement officiel (KBIS)',
        type: 'file',
        variant: 'area',
      },
      {
        color: 'primary',
        content: 'Dernière synchronisation Evoliz il y a 3 jours, VTest il y a 12 jours.',
        icon: 'i-lucide-bell',
        key: 'syncNote',
        type: 'info',
      },
      { key: 'preferences', label: 'Préférences', type: 'section' },
      {
        key: 'language',
        label: 'Langue',
        layout: { labelPosition: 'left', labelWidth: 160 },
        options: [
          { label: 'Français', value: 'fr' },
          { label: 'English', value: 'en' },
        ],
        type: 'select',
      },
      {
        key: 'timezone',
        label: 'Fuseau horaire',
        layout: { labelPosition: 'left', labelWidth: 160 },
        options: [
          { label: 'Europe/Paris', value: 'Europe/Paris' },
          { label: 'Europe/Madrid', value: 'Europe/Madrid' },
        ],
        type: 'select',
      },
    ],
    header: {
      description: 'Masques, préfixes, formats de nombre, labels à gauche et descriptions.',
      eyebrow: 'Démo',
      title: 'Propriétés de parité',
    },
    modal: { size: 'lg' },
  })
}

export const parityFormInput = {
  accountType: 'customer',
  erpId: 'EVZ-48213',
  language: 'fr',
  levels: ['A2', 'B1'],
  listPrice: 129,
  productName: 'TOEIC Listening & Reading',
  rate: 0.9214,
  scope: 'filters',
  siren: '812345678',
  unitPrice: 129,
  vat: 'FR12345678901',
  volume: 1200,
}
